<div class="pwf_header">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="26%"><img src="images/logo.jpg" alt="" width="250" height="38" /></td>
        <td width="74%"><table width="100%" border="0" cellpadding="2">
          <tr>
            <td width="39%"><div align="right"><asp:ImageButton ID="imgButtonHom" runat="server" ImageUrl="images/bt_home.gif" /></div></td>
            <td width="24%"><div align="right"> <asp:ImageButton ID="imgButtonSearch" runat="server" ImageUrl="images/bt_help.gif" /></div></td>
            <td width="37%" valign="bottom"><div align="center">Telephone: <asp:Label ID="lblPhoneNumber" runat="server" Text="XXXXXXXXXX"></asp:Label> </div></td>
          </tr>
        </table></td>
      </tr>
  </table>
	 
    
</div>