<!--Header-->
<div class="header">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td class="style1" style="width: 17%; height: 22px;">
        <img src="images/logo.jpg" alt="" width="221" height="33"/>




      </td>
      <td class="style1" style="width: 40%; height: 22px;">
        <div class="style1">
          <strong>&nbsp; Get together. Buy together</strong>
        </div>
      </td>
      <td width="74%" style="height: 22px">
        <div align="right">
          <strong>
            <a href="login.aspx" class="style1">Sign Up</a>
          </strong>| <a href="login.aspx">Login</a> | <a href="indexHelp.aspx">Help</a> <img src="images/spacer.gif" height="2" width="30"/>
        </div>
      </td>
    </tr>
    <tr>
      <td height="39" colspan="3" class="line_background_top" span="" >
        <div id="navcontainer">
          <ul id="navlist">
            <li id="active">
              <a href="#" id="current">
                Home
              </a>
            </li>
            <li>
              <a href="indexShopper.aspx">
                <span style="color:#E0691A">How it works</span>
              </a>
            </li>
            <li>
              <a href="indexBusiness.aspx">Business Solutions</a>
            </li>
            <li>
              <a href="MemberPage.aspx">My Account</a>
            </li>
            <li>
              <a href="indexHelp.aspx">
                Help
              </a>
            </li>
          </ul>
        </div>
      </td>
    </tr>
  </table>

</div>
<!--end of Header-->