<!--Footer-->
  <div class="full_width">
 <div class="footer">
 <table>
 <tr>
 <td><a href="aboutUs.aspx">About Us </a> | </td>
 <td><a href="contactus.aspx">Contact Us</a> | </td>
 <td><a href="useragreement.aspx">Terms and Conditions</a> | </td>
 <td><a href="#">Blog </a> |</td>
 <td><a href="Feedback.aspx">Feedback</a> |</td>
<td>
     <a href="http://www.spidermarkets.com/platform.html">
       <B>R&D by Spidermarkets</B>
     </a>
   </td>
 </tr>
 
 </table>
 </div> 
 </div>
  <!--End of Footer--> 


